name: dad_project_2
description: DAD / Project II / 5f2a95e0-7191-4b64-9ba5-0b7d9611e127

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  badges: ^2.0.3
  flutter:
    sdk: flutter

  http: ^0.13.5
  flutter_riverpod: ^1.0.4
  go_router: ^5.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # this tells flutter that there is a folder assets with a file data.json
  assets:
    - assets/data.json
